import { ClassItem, Trainer, MembershipPlan, Testimonial, BlogPost } from "./types";

export const classes: ClassItem[] = [
  {
    id: "1",
    name: "HIIT Inferno",
    category: "HIIT",
    level: "Advanced",
    trainer: "Marcus Rivera",
    time: "06:00 AM",
    duration: "45 min",
    day: "Mon, Wed, Fri",
    capacity: 20,
    booked: 14,
    image: "/HIIT Inferno.jpg",
    description: "High-intensity interval training to torch calories and build endurance.",
    calories: "600-800",
  },
  {
    id: "2",
    name: "Power Yoga Flow",
    category: "Yoga",
    level: "Beginner",
    trainer: "Aria Chen",
    time: "07:30 AM",
    duration: "60 min",
    day: "Tue, Thu, Sat",
    capacity: 25,
    booked: 18,
    image: "/Power Yoga Flow.jpg",
    description: "Enhance flexibility and mindfulness with flowing yoga sequences.",
    calories: "300-400",
  },
  {
    id: "3",
    name: "CrossFit Challenge",
    category: "CrossFit",
    level: "Advanced",
    trainer: "Jake Thompson",
    time: "09:00 AM",
    duration: "60 min",
    day: "Mon-Sat",
    capacity: 15,
    booked: 12,
    image: "/CrossFit Challenge.jpg",
    description: "Functional movements performed at high intensity for total body conditioning.",
    calories: "700-900",
  },
  {
    id: "4",
    name: "Boxing Fundamentals",
    category: "Boxing",
    level: "Beginner",
    trainer: "Diana Ortiz",
    time: "05:00 PM",
    duration: "50 min",
    day: "Mon, Wed, Fri",
    capacity: 18,
    booked: 8,
    image: "/Boxing Fundamentals.jpg",
    description: "Learn boxing techniques while getting an incredible full-body workout.",
    calories: "500-700",
  },
  {//start
    id: "5",
    name: "Strength & Conditioning",
    category: "Strength",
    level: "Intermediate",
    trainer: "Marcus Rivera",
    time: "06:30 AM",
    duration: "55 min",
    day: "Tue, Thu, Sat",
    capacity: 20,
    booked: 15,
    image: "/Strength & Conditioning.jpg",
    description: "Build raw strength with compound lifts and conditioning drills.",
    calories: "500-650",
  },
  {
    id: "6",
    name: "Spin Fury",
    category: "Cycling",
    level: "Intermediate",
    trainer: "Sarah Blake",
    time: "06:00 PM",
    duration: "45 min",
    day: "Mon-Fri",
    capacity: 30,
    booked: 22,
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=80",
    description: "High-energy indoor cycling with music-driven intensity peaks.",
    calories: "550-750",
  },
  {
    id: "7",
    name: "Pilates Core",
    category: "Pilates",
    level: "Beginner",
    trainer: "Aria Chen",
    time: "08:00 AM",
    duration: "50 min",
    day: "Mon, Wed, Fri",
    capacity: 22,
    booked: 10,
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80",
    description: "Strengthen your core and improve posture with controlled movements.",
    calories: "250-350",
  },
  {
    id: "8",
    name: "Muay Thai Striking",
    category: "Martial Arts",
    level: "Advanced",
    trainer: "Diana Ortiz",
    time: "07:00 PM",
    duration: "60 min",
    day: "Tue, Thu, Sat",
    capacity: 16,
    booked: 14,
    image: "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800&q=80",
    description: "Authentic Muay Thai techniques for striking and clinch work.",
    calories: "700-850",
  },
];

export const trainers: Trainer[] = [
  {
    id: "1",
    name: "Marcus Rivera",
    specialty: "HIIT & Strength",
    experience: "12+ years",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    socials: { instagram: "#", twitter: "#", linkedin: "#" },
    bio: "Former competitive athlete turned elite coach. Specializes in transforming bodies through science-backed HIIT protocols.",
    certifications: ["NASM-CPT", "CSCS", "Precision Nutrition L1"],
  },
  {
    id: "2",
    name: "Aria Chen",
    specialty: "Yoga & Pilates",
    experience: "8+ years",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1594381898411-846e7d193883?w=600&q=80",
    socials: { instagram: "#", linkedin: "#" },
    bio: "Certified yoga therapist with a passion for making mind-body practices accessible to everyone.",
    certifications: ["RYT-500", "PMA-CPT", "Yoga Alliance"],
  },
  {
    id: "3",
    name: "Jake Thompson",
    specialty: "CrossFit & Functional Training",
    experience: "10+ years",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1583468982228-19f19164aee2?w=600&q=80",
    socials: { instagram: "#", twitter: "#" },
    bio: "CrossFit Level 3 trainer who has competed at the regional level. Believes in pushing limits safely.",
    certifications: ["CF-L3", "USAW L2", "CrossFit Gymnastics"],
  },
  {
    id: "4",
    name: "Diana Ortiz",
    specialty: "Boxing & Muay Thai",
    experience: "15+ years",
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=600&q=80",
    socials: { instagram: "#", twitter: "#", linkedin: "#" },
    bio: "Professional fighter turned coach. Brings real fight experience to every training session.",
    certifications: ["USA Boxing Coach", "IFMA Certified", "First Aid/CPR"],
  },
  {
    id: "5",
    name: "Sarah Blake",
    specialty: "Cycling & Cardio",
    experience: "7+ years",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80",
    socials: { instagram: "#", linkedin: "#" },
    bio: "Music-driven spin instructor who creates immersive cardio experiences that feel like a party.",
    certifications: ["Schwinn Certified", "ACE-GFI", "CPR/AED"],
  },
  {
    id: "6",
    name: "Raj Patel",
    specialty: "Flexibility & Mobility",
    experience: "9+ years",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1550345332-09e3ac987658?w=600&q=80",
    socials: { instagram: "#", twitter: "#" },
    bio: "Movement specialist focused on helping clients achieve pain-free, functional movement patterns.",
    certifications: ["FMS L2", "FRCms", "NKT L1"],
  },
];

export const membershipPlans: MembershipPlan[] = [
  {
    id: "basic",
    name: "Basic",
    price: 29,
    period: "month",
    features: [
      "Access to gym floor",
      "Locker room access",
      "3 classes per week",
      "Basic fitness assessment",
      "Open gym hours",
    ],
    highlighted: false,
    color: "#A3A3A3",
  },
  {
    id: "pro",
    name: "Pro",
    price: 59,
    period: "month",
    features: [
      "Unlimited classes",
      "Priority booking",
      "Locker room + sauna",
      "Monthly body composition scan",
      "2 personal training sessions",
      "Guest passes (2/month)",
      "Nutrition consultation",
    ],
    highlighted: true,
    color: "#F97316",
  },
  {
    id: "elite",
    name: "Elite",
    price: 99,
    period: "month",
    features: [
      "All Pro features",
      "Unlimited personal training",
      "Private locker",
      "Meal plan customization",
      "Recovery zone access",
      "Exclusive Elite events",
      "24/7 facility access",
      "Partner discounts",
    ],
    highlighted: false,
    color: "#D4AF37",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Alex Morgan",
    role: "Lost 45 lbs in 6 months",
    content:
      "IRONPULSE completely changed my life. The trainers are incredibly motivating, and the community keeps me coming back every single day. Never thought I'd actually enjoy working out!",
    rating: 5,
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    role: "Elite Member since 2023",
    content:
      "The Elite membership is worth every penny. Having unlimited personal training has accelerated my progress beyond what I thought possible. The facilities are world-class.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
  },
  {
    id: "3",
    name: "Mike Chen",
    role: "CrossFit Competitor",
    content:
      "As someone who competes, I need a gym that pushes me. IRONPULSE's CrossFit program and Jake's coaching have taken my performance to the next level. The equipment is top-notch.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
  },
  {
    id: "4",
    name: "Emily Davis",
    role: "Yoga Enthusiast",
    content:
      "Aria's yoga classes are transformative. I came for the physical benefits but stayed for the mental clarity. The studio space is serene and beautifully designed.",
    rating: 4,
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "5 HIIT Workouts You Can Do Anywhere",
    excerpt: "High-intensity interval training doesn't require a gym. Here are 5 killer workouts you can do in your living room.",
    content: "Full content here...",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80",
    date: "2025-06-10",
    author: "Marcus Rivera",
    category: "Workouts",
    slug: "5-hiit-workouts-anywhere",
  },
  {
    id: "2",
    title: "The Ultimate Guide to Gym Nutrition",
    excerpt: "Fuel your gains with proper nutrition. Learn what to eat before and after your workouts for maximum results.",
    content: "Full content here...",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80",
    date: "2025-06-05",
    author: "Sarah Blake",
    category: "Nutrition",
    slug: "ultimate-gym-nutrition-guide",
  },
  {
    id: "3",
    title: "Recovery: The Most Overlooked Training Pillar",
    excerpt: "Rest and recovery are just as important as the workout itself. Here's how to optimize your recovery routine.",
    content: "Full content here...",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    date: "2025-05-28",
    author: "Aria Chen",
    category: "Recovery",
    slug: "recovery-overlooked-training-pillar",
  },
];
